name: Test SSH Connection

on: [workflow_dispatch] # Позволяет запустить тест вручную кнопкой

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Timeweb
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo "Привет от GitHub! SSH ключ успешно работает!"
